server:
  port: 8080

spring:
  application:
    name: sdb
  datasource:
    url: jdbc:postgresql://localhost:5432/sdb
    username: postgres
    password: 11347813
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#  freemarker:
#    request-context-attribute: request
#    cache: false
#    template-loader-path: classpath:/templates/
#    suffix: .ftl
#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false

logging:
  level:
    org:
      hibernate:
        type: trace

